[package]
name = "chunked-decoder"
version = "0.1.2"
edition = "2024"
description = "A streaming parser for Transfer-Encoding: chunked HTTP/1.1 and HTTPS request bodies."
license = "Apache-2.0"
repository = "https://github.com/Cheapstar/chunked-decoder.git"
readme = "README.md"
keywords = ["http", "chunked", "parser", "decoder","Transfer-Encoding"]
categories = ["web-programming", "parser-implementations"]
rust-version = "1.85"

[dependencies]
